  name: renuoil_undian_20
  description: ReNuOil App - Used Cooking Oil Recycling Platform
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.2

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0

  flutter:
    uses-material-design: true
    assets:
    - assets/images/kartu_rno.png
    - assets/images/logo_rno.png
    - assets/images/map_rno.jpeg
    - assets/images/maskot_rno.png
    - assets/images/ricci_ai_photo.jpeg
